// Owner: @SDET | Scope: Shopify dev-dashboard store registry
//
// Source of truth: shopifyStores.json — generated by `npm run shopify:scrape-stores`.
// This module loads the JSON at runtime via fs (rather than `import`) to avoid
// requiring `resolveJsonModule` in tsconfig.

import fs from 'fs';
import path from 'path';

export interface ShopifyStore {
  /** Human-readable store name as it appears on the dev dashboard */
  name: string;
  /** URL slug — appears in admin.shopify.com/store/<handle> */
  handle: string;
  /** Direct URL to the store admin */
  adminUrl: string;
}

const STORES_PATH = path.resolve(__dirname, 'shopifyStores.json');

export function loadShopifyStores(): ShopifyStore[] {
  try {
    if (!fs.existsSync(STORES_PATH)) return [];
    // Strip a UTF-8 BOM if present (some editors / git hooks write one).
    const raw = fs.readFileSync(STORES_PATH, 'utf-8').replace(/^﻿/, '').trim();
    if (!raw) return [];
    const parsed: unknown = JSON.parse(raw);
    return Array.isArray(parsed) ? (parsed as ShopifyStore[]) : [];
  } catch (err) {
    console.error(`[shopifyStoreslist] Failed to load JSON: ${(err as Error).message}`);
    return [];
  }
}

export const SHOPIFY_STORES: ShopifyStore[] = loadShopifyStores();
